export default [
  // season 1
  {
    id: 1,
    season: 1,
    episode: 1,
    title: "Both Ways",
    includesTim: true,
  },
  {
    id: 2,
    season: 1,
    episode: 1,
    title: "Has This Ever Happened to You?",
    includesTim: true,
  },
  {
    id: 3,
    season: 1,
    episode: 1,
    title: "Baby of the Year",
    includesTim: false,
  },
  {
    id: 4,
    season: 1,
    episode: 1,
    title: "Instagram",
    includesTim: false,
  },
  {
    id: 5,
    season: 1,
    episode: 1,
    title: "Gift Receipt",
    includesTim: true,
  },
  {
    id: 6,
    season: 1,
    episode: 2,
    title: "Biker Guy",
    includesTim: true,
  },
  {
    id: 7,
    season: 1,
    episode: 2,
    title: "River Mountain High, Part 1",
    includesTim: true,
  },
  {
    id: 8,
    season: 1,
    episode: 2,
    title: "Wilson's Toupees",
    includesTim: false,
  },
  {
    id: 9,
    season: 1,
    episode: 2,
    title: "Pink Bag",
    includesTim: true,
  },
  {
    id: 10,
    season: 1,
    episode: 2,
    title: "River Mountain High, Part 2",
    includesTim: true,
  },
  {
    id: 11,
    season: 1,
    episode: 2,
    title: "The Man",
    includesTim: true,
  },
  {
    id: 12,
    season: 1,
    episode: 3,
    title: "Which Hand",
    includesTim: true,
  },
  {
    id: 13,
    season: 1,
    episode: 3,
    title: "Focus Group",
    includesTim: true,
  },
  {
    id: 14,
    season: 1,
    episode: 3,
    title: "Laser Spine Specialists",
    includesTim: true,
  },
  {
    id: 15,
    season: 1,
    episode: 3,
    title: "New Joe",
    includesTim: false,
  },
  {
    id: 16,
    season: 1,
    episode: 3,
    title: "Game Night",
    includesTim: true,
  },
  {
    id: 17,
    season: 1,
    episode: 4,
    title: "Lifetime Achievement Award",
    includesTim: true,
  },
  {
    id: 18,
    season: 1,
    episode: 4,
    title: "Christmas Carol",
    includesTim: false,
  },
  {
    id: 19,
    season: 1,
    episode: 4,
    title: "Nachos",
    includesTim: true,
  },
  {
    id: 20,
    season: 1,
    episode: 4,
    title: "Honk if You're Horny",
    includesTim: true,
  },
  {
    id: 21,
    season: 1,
    episode: 5,
    title: "Brooks Brothers",
    includesTim: true,
  },
  {
    id: 22,
    season: 1,
    episode: 5,
    title: "Choking",
    includesTim: true,
  },
  {
    id: 23,
    season: 1,
    episode: 5,
    title: "New Printer",
    includesTim: true,
  },
  {
    id: 24,
    season: 1,
    episode: 5,
    title: "The Day Robert Palin's Murdered Me",
    includesTim: true,
  },
  {
    id: 25,
    season: 1,
    episode: 5,
    title: "The Babysitter",
    includesTim: true,
  },
  {
    id: 26,
    season: 1,
    episode: 6,
    title: "Fenton's Stable and Horse Ranch",
    includesTim: false,
  },
  {
    id: 27,
    season: 1,
    episode: 6,
    title: "Chunky",
    includesTim: true,
  },
  {
    id: 28,
    season: 1,
    episode: 6,
    title: "Bozo Part 1",
    includesTim: true,
  },
  {
    id: 29,
    season: 1,
    episode: 6,
    title: "Baby Shower",
    includesTim: true,
  },
  {
    id: 30,
    season: 1,
    episode: 6,
    title: "Bozo Part 2",
    includesTim: true,
  },
  {
    id: 31,
    season: 1,
    episode: 6,
    title: "Party House",
    includesTim: true,
  },
  // season 2
  {
    id: 32,
    season: 2,
    episode: 1,
    title: "Lunch Meeting",
    includesTim: true,
  },
  {
    id: 33,
    season: 2,
    episode: 1,
    title: "Coffin Flop",
    includesTim: true,
  },
  {
    id: 34,
    season: 2,
    episode: 1,
    title: "Prank Show",
    includesTim: true,
  },
  {
    id: 35,
    season: 2,
    episode: 1,
    title: "Little Buff Boys",
    includesTim: false,
  },
  {
    id: 36,
    season: 2,
    episode: 1,
    title: "Ghost Tour",
    includesTim: true,
  },
  {
    id: 37,
    season: 2,
    episode: 2,
    title: "The Capital Room",
    includesTim: false,
  },
  {
    id: 38,
    season: 2,
    episode: 2,
    title: "Dan Flashes",
    includesTim: true,
  },
  {
    id: 39,
    season: 2,
    episode: 2,
    title: "Diner Wink",
    includesTim: true,
  },
  {
    id: 40,
    season: 2,
    episode: 2,
    title: "Shops at the Creek",
    includesTim: false,
  },
  {
    id: 41,
    season: 2,
    episode: 2,
    title: "Baby Cries",
    includesTim: true,
  },
  {
    id: 42,
    season: 2,
    episode: 3,
    title: "Graham's Lorelei Lounge",
    includesTim: true,
  },
  {
    id: 43,
    season: 2,
    episode: 3,
    title: "Detective Crashmore Trailer",
    includesTim: false,
  },
  {
    id: 44,
    season: 2,
    episode: 3,
    title: "HD Vac Commercial",
    includesTim: true,
  },
  {
    id: 45,
    season: 2,
    episode: 3,
    title: "Detective Crashmore Press Junket",
    includesTim: false,
  },
  {
    id: 46,
    season: 2,
    episode: 3,
    title: "Qualstarr Trial",
    includesTim: true,
  },
  {
    id: 47,
    season: 2,
    episode: 4,
    title: "Wife Joke",
    includesTim: false,
  },
  {
    id: 48,
    season: 2,
    episode: 4,
    title: "Friends Weekend",
    includesTim: true,
  },
  {
    id: 49,
    season: 2,
    episode: 4,
    title: "Calico Cut Pants",
    includesTim: true,
  },
  {
    id: 50,
    season: 2,
    episode: 5,
    title: "Parking Lot",
    includesTim: true,
  },
  {
    id: 51,
    season: 2,
    episode: 5,
    title: "Del Frisco's Double Eagle",
    includesTim: false,
  },
  {
    id: 52,
    season: 2,
    episode: 5,
    title: "Joanie's Birthday",
    includesTim: true,
  },
  {
    id: 53,
    season: 2,
    episode: 5,
    title: "Dave Campor",
    includesTim: false,
  },
  {
    id: 54,
    season: 2,
    episode: 5,
    title: "Mars Restaurant",
    includesTim: false,
  },
  {
    id: 55,
    season: 2,
    episode: 6,
    title: "Dave Suit",
    includesTim: true,
  },
  {
    id: 56,
    season: 2,
    episode: 6,
    title: "Driver's Ed",
    includesTim: true,
  },
  {
    id: 57,
    season: 2,
    episode: 6,
    title: "Tammy Craps",
    includesTim: false,
  },
  {
    id: 58,
    season: 2,
    episode: 6,
    title: "Big Wave",
    includesTim: true,
  },
  {
    id: 59,
    season: 2,
    episode: 6,
    title: "Claire's",
    includesTim: false,
  },
];
